### ISSUE TITLE
ClientAbortException

### ISSUE THREAD

**Issue by lcw3176** [lcw3176/MapshotServer#1]
class org.apache.catalina.connector.ClientAbortException    
    org.apache.catalina.connector.ClientAbortException: java.net.SocketTimeoutException
    at org.apache.catalina.connector.OutputBuffer.realWriteBytes(OutputBuffer.java:353)
    at org.apache.catalina.connector.OutputBuffer.appendByteArray(OutputBuffer.java:753)
    at org.apache.catalina.connector.OutputBuffer.append(OutputBuffer.java:682)
    at org.apache.catalina.connector.OutputBuffer.writeBytes(OutputBuffer.java:388)
    at org.apache.catalina.connector.OutputBuffer.write(OutputBuffer.java:366)
    at org.apache.catalina.connector.CoyoteOutputStream.write(CoyoteOutputStream.java:96)
    at org.apache.catalina.connector.CoyoteOutputStream.write(CoyoteOutputStream.java:89)
    at org.springframework.util.StreamUtils.copy(StreamUtils.java:129)
    at org.springframework.http.converter.ByteArrayHttpMessageConverter.writeInternal(ByteArrayHttpMessageConverter.java:70)
    at org.springframework.http.converter.ByteArrayHttpMessageConverter.writeInternal(ByteArrayHttpMessageConverter.java:39)
    at org.springframework.http.converter.AbstractHttpMessageConverter.write(AbstractHttpMessageConverter.java:227)
    at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMethodProcessor.java:293)
    at org.springframework.web.servlet.mvc.method.annotation.HttpEntityMethodProcessor.handleReturnValue(HttpEntityMethodProcessor.java:219)
    at org.springframework.web.method.support.HandlerMethodReturnValueHandlerComposite.handleReturnValue(HandlerMethodReturnValueHandlerComposite.java:78)
    at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:135)
    at..

서버에서 응답하기 전에 클라이언트 요청이 중단된 상황으로 생각됨.
아마 mapshot 서비스에 처음 접속하면 서버를 깨우기 위해 헤로쿠 서버에 요청을 날리는데, 이 상황에서 새로고침을 하거나
카카오 지도 응답 속도가 느려서 지도를 받을 때 문제가 생겼을 것으로 생각됨.

**Comment by lcw3176** [comment]
헤로쿠 타임아웃에 걸린 상황으로 판정됨.
현재 ChromeDriver 관련 객체들을 빈으로 등록해서 속도는 훨씬 향상되었음.
이제 타임아웃 에러는 거의 줄어들 것으로 예상됨.
하지만 빈으로 등록하면 헤로쿠 R14 메모리 문제가 나긴 하지만, 
최대한 서버에 불필요한 요청을 줄여서 2~3시간 사이에 한번은 
서버가 재부팅 될 수 있도록 할 에정.
