### ISSUE TITLE
WebDriverException

### ISSUE THREAD

**Issue by lcw3176** [lcw3176/MapshotServer#2]
class org.openqa.selenium.WebDriverException
org.openqa.selenium.WebDriverException: The driver server has unexpectedly died!
Build info: version: '4.1.1', revision: 'e8fcc2cecf'
System info: host: '197dc185-02ad-4dba-9847-fc6c23d4a714', ip: '172.17.110.242', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-1097-aws', java.version: '15.0.5'
Driver info: com.joebrooks.mapshotserver.domain.map.kakao.util.CustomChromeDriver
Command: [8cd05484360777ff7b8a620004a1c75b, close {}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 97.0.4692.99, chrome: {chromedriverVersion: 97.0.4692.71 (adefa7837d02a..., userDataDir: /tmp/.com.google.Chrome.rlfP5g}, goog:chromeOptions: {debuggerAddress: localhost:36783}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), se:cdp: ws://localhost:36783/devtoo..., se:cdpVersion: 97.0.4692.99, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
    at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:148)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:598)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:602)
    at org.openqa.selenium.remote.RemoteWebDriver.close(RemoteWebDriver.java:428)
    at com.joebrooks.mapshotserver.domain.map.kakao.service.ChromeDriverService.onClose(ChromeDriverService.j...

웹 드라이버 갑작스러운 종료 에러.

**Comment by lcw3176** [comment]
지도 생성 중에 헤로쿠 타임아웃에 걸린 것으로 추정됨. 서버 스펙이 무료 버전이라 워낙 낮은 데다가 30초 시간제한도 있어서 클라우드 서비스를 옮기지 않는 이상 마땅한 해답이 안보임. 그나마 다행인 건 1km 반경의 카카오 지도를 생성할 때만 가끔 발생하는 에러라는 것. 만약 오라클 클라우드 프리티어 서버로 옮긴다면 사라질 에러로 보임.
